// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwwgmofueugonsbgvqtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3d2dtb2Z1ZXVnb25zYmd2cXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTA5OTEsImV4cCI6MjA2MjYyNjk5MX0.5ZYy76tzIs7wImMhPlRnSy-yEZeXjP-hGoli_QWzoYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);